### ISSUE TITLE
Performance drop with GEMM for matrix sizes > 6500 and double precision

### ISSUE THREAD

**Issue by MigMuc** [CNugteren/CLBlast#134]
I noticed an impact on performance with the clblast_client program using double precision which does not appear for the clBLAS part. 
```
                                                                                                                                              | <--     CLBlast       --> | <--       clBLAS        --> |
        m;        n;        k;   layout;   transA;   transB;      lda;      ldb;      ldc;     offa;     offb;     offc;    alpha;     beta;     ms_1; GFLOPS_1;    GBs_1;     ms_2; GFLOPS_2;    GBs_2
     6500;     6500;     6500;      101;      111;      111;     6500;     6500;     6500;        0;        0;        0; 2.000000; 2.000000;  3928.90;    139.8;      0.3;  3174.45;    173.0;      0.4
     6550;     6550;     6550;      101;      111;      111;     6550;     6550;     6550;        0;        0;        0; 2.000000; 2.000000; 25413.83;     22.1;      0.1;  2833.48;    198.4;      0.5
     6600;     6600;     6600;      101;      111;      111;     6600;     6600;     6600;        0;        0;        0; 2.000000; 2.000000; 26123.41;     22.0;      0.1;  4006.38;    143.5;      0.3
     6650;     6650;     6650;      101;      111;      111;     6650;     6650;     6650;        0;        0;        0; 2.000000; 2.000000; 26392.68;     22.3;      0.1;  2961.49;    198.6;      0.5
     6700;     6700;     6700;      101;      111;      111;     6700;     6700;     6700;        0;        0;        0; 2.000000; 2.000000; 27233.97;     22.1;      0.1;  3020.21;    199.2;      0.5
     6750;     6750;     6750;      101;      111;      111;     6750;     6750;     6750;        0;        0;        0; 2.000000; 2.000000; 27699.47;     22.2;      0.1;  3074.35;    200.1;      0.5
     6800;     6800;     6800;      101;      111;      111;     6800;     6800;     6800;        0;        0;        0; 2.000000; 2.000000; 28399.04;     22.1;      0.1;  3273.24;    192.1;      0.5
     6850;     6850;     6850;      101;      111;      111;     6850;     6850;     6850;        0;        0;        0; 2.000000; 2.000000; 29224.54;     22.0;      0.1;  3222.29;    199.5;      0.5
```
Is this maybe related to the allowed max. Mem allocation on my device which is restricted to about 1.3 GB? I am using a Tonga device (Radeon R9 380 with 2GB Memory). But on the other hand clBLAS almost reaches peak performance ~218 GFLOP (DP) for matrix sizes up to 8k.

**Comment by CNugteren** [comment]
That doesn't look good. Is CLBlast fast for all sizes up to 6500, or are there performance drops earlier on as well? You could try to run the tuner for sizes 6500 and see what it reports and then re-run it for size 6550 and see if it also drops. If it both shows good performance it just means the tuning parameters are not optimized for larger sizes. If the tuner is also slow for 6550 and higher it might mean that the CLBlast kernel is just not suited.

I'll investigate myself as well, I have a R9 M370X, perhaps it shows similar behaviour.

**Comment by MigMuc** [comment]
I have included the SGEMM and DGEMM results from the performance scripts. They are generated with default tuning parameters from the CLBlast tuning script.
[SGEMM.pdf](https://github.com/CNugteren/CLBlast/files/736909/SGEMM.pdf)
[DGEMM.pdf](https://github.com/CNugteren/CLBlast/files/736910/DGEMM.pdf)
I will try to run the tuner for size 6500 and do the benchmark again with the new tuning results.

**Comment by MigMuc** [comment]
Tuning for matrix sizes m=n=k=6500 freezes my screen and tuning get's stuck in the very first parameter set after the reference call has been completed. The size which works is 5120. But adding these results to the database I get the following error:
```database] Loading database from '../scripts/database/database.json'
[database] Processing './clblast_xgemm_1_64.json' with 0 new items
[database] Processing './clblast_xgemm_2_64.json' with 0 new items
[database] Saving database to '../scripts/database/database.json'
[database] Calculating the best results per device/kernel...
[database] Calculating the default values...
[database] Warning: No common kernels for: Intel;CPU;3232;xgemm;Xgemm;1024;1024;1024;2+0.5i;2+0.5i at all
[database] Warning: No common kernels for: Intel;CPU;32;xgemm;Xgemm;1024;1024;1024;2.000000;2.000000 at all
[database] Warning: No common kernels for: Intel;CPU;6464;xgemm;Xgemm;1024;1024;1024;2+0.5i;2+0.5i at all
[ERROR] Entries for a single kernel with multiple argument values: AMD;GPU;64;xgemm;Xgemm
Traceback (most recent call last):
  File "../scripts/database/database.py", line 104, in <module>
    main(sys.argv[1:])
  File "../scripts/database/database.py", line 89, in main
    database_defaults = defaults.calculate_defaults(database, cl_args.verbose)
  File "/home/miguel/Downloads/CLBlast-0.10.0/scripts/database/database/defaults.py", line 90, in calculate_defaults
    assert len(group) == 1
AssertionError```

**Comment by CNugteren** [comment]
Thanks for running all the benchmarks!

First about the tuner: indeed, it is not possible to automatically add tuning results to the database with different matrix/vector sizes. I hope to soon implement the request in #130, which will allow passing tuning parameters programmatically. You can of course still set tuning parameters manually in the database files in `src/database/kernels/`.

About the benchmarks you ran: So it seems that CLBlast is faster in most cases compared to clBLAS for your device. For some cases it is slower, but not that much. The only real issue is the 8192 case for double-precision, in which CLBlast is really really slow. This is probably the same thing you are noticing, but you actually found out this issue already starts at ~6500.

Now about what could be causing it: I can understand that for smaller sizes the kernel is slower because of less parallelism, but more parallelism should only be beneficial (or at least not detrimental) for the GPU. Nothing else changes, the kernel binary is the same and the amount of threads per workgroup remains the same. So the only other thing I can come up with as a possible explanation is 'partition camping', an issue still present in modern AMD GPUs. I also discussed this in #53 and 'solved' it using [the staggered indices suggested by an AMD article](http://developer.amd.com/tools-and-sdks/opencl-zone/amd-accelerated-parallel-processing-app-sdk/opencl-optimization-guide/#50401334_pgfId-472340). However, it might well be that for larger matrices this starts to become an issue again.

As a quick test you could disable the staggered indices by commenting out line 113 (development branch) of `src/routine.cpp`. Perhaps that changes behaviour?

I cannot reproduce your issue for double precision (because it is super slow anyway on my mobile AMD R9 M370X GPU), but I can see some performance drop for larger values for single precision:
```
                                                                                                                                             | <--       CLBlast       --> |
        m;        n;        k;   layout;   transA;   transB;      lda;      ldb;      ldc;     offa;     offb;     offc;    alpha;     beta;     ms_1; GFLOPS_1;    GBs_1
     3000;     3000;     3000;      101;      111;      111;     3000;     3000;     3000;        0;        0;        0; 2.000000; 2.000000;   115.92;    465.8;      1.2
     4000;     4000;     4000;      101;      111;      111;     4000;     4000;     4000;        0;        0;        0; 2.000000; 2.000000;   252.32;    507.3;      1.0
     5000;     5000;     5000;      101;      111;      111;     5000;     5000;     5000;        0;        0;        0; 2.000000; 2.000000;   492.36;    507.8;      0.8
     6000;     6000;     6000;      101;      111;      111;     6000;     6000;     6000;        0;        0;        0; 2.000000; 2.000000;   823.04;    524.9;      0.7
     7000;     7000;     7000;      101;      111;      111;     7000;     7000;     7000;        0;        0;        0; 2.000000; 2.000000;  1302.50;    526.7;      0.6
     8000;     8000;     8000;      101;      111;      111;     8000;     8000;     8000;        0;        0;        0; 2.000000; 2.000000;  1922.98;    532.5;      0.5
     9000;     9000;     9000;      101;      111;      111;     9000;     9000;     9000;        0;        0;        0; 2.000000; 2.000000;  2928.46;    497.9;      0.4
    10000;    10000;    10000;      101;      111;      111;    10000;    10000;    10000;        0;        0;        0; 2.000000; 2.000000;  4424.57;    452.0;      0.4
    11000;    11000;    11000;      101;      111;      111;    11000;    11000;    11000;        0;        0;        0; 2.000000; 2.000000;  6041.07;    440.7;      0.3
    12000;    12000;    12000;      101;      111;      111;    12000;    12000;    12000;        0;        0;        0; 2.000000; 2.000000;  7723.28;    447.5;      0.3
    13000;    13000;    13000;      101;      111;      111;    13000;    13000;    13000;        0;        0;        0; 2.000000; 2.000000; 10693.02;    410.9;      0.3
```
After 13K, I start to run into memory-size issues.

**Comment by MigMuc** [comment]
I downloaded the development branch and set the variable mentioned above to 
```source_string += "#define USE_STAGGERED_INDICES 0\n";```
Then running the client I get the following:
```       | <--       CLBlast       --> |
        m;        n;        k;   layout;   transA;   transB;      lda;      ldb;      ldc;     offa;     offb;     offc;    alpha;     beta;     ms_1; GFLOPS_1;    GBs_1
     3000;     3000;     3000;      101;      111;      111;     3000;     3000;     3000;        0;        0;        0; 2.000000; 2.000000;   272.36;    198.3;      1.1
     4000;     4000;     4000;      101;      111;      111;     4000;     4000;     4000;        0;        0;        0; 2.000000; 2.000000;   628.10;    203.8;      0.8
     5000;     5000;     5000;      101;      111;      111;     5000;     5000;     5000;        0;        0;        0; 2.000000; 2.000000;  1249.03;    200.2;      0.6
     6000;     6000;     6000;      101;      111;      111;     6000;     6000;     6000;        0;        0;        0; 2.000000; 2.000000;  2350.49;    183.8;      0.5
     7000;     7000;     7000;      101;      111;      111;     7000;     7000;     7000;        0;        0;        0; 2.000000; 2.000000; 54087.86;     12.7;      0.0
CLBlast: OpenCL error: clEnqueueNDRangeKernel: -4
terminate called after throwing an instance of 'std::runtime_error'
  what():  CLBlast error: -4
Abgebrochen (Speicherabzug geschrieben)```

**Comment by CNugteren** [comment]
That last issue (error -4) is most probably because of the memory size limit of your device, I'll have to see if I can handle that properly. But the performance also seems to go down after 6000. Can you re-run the first experiment you did?

**Comment by MigMuc** [comment]
```                                                                                                                                             | <--       CLBlast       --> | <--       clBLAS        --> |
        m;        n;        k;   layout;   transA;   transB;      lda;      ldb;      ldc;     offa;     offb;     offc;    alpha;     beta;     ms_1; GFLOPS_1;    GBs_1;     ms_2; GFLOPS_2;    GBs_2
     6400;     6400;     6400;      101;      111;      111;     6400;     6400;     6400;        0;        0;        0; 2.000000; 2.000000;  4998.62;    104.9;      0.3;  2422.50;    216.4;      0.5
     6450;     6450;     6450;      101;      111;      111;     6450;     6450;     6450;        0;        0;        0; 2.000000; 2.000000; 16352.57;     32.8;      0.1;  2706.18;    198.3;      0.5
     6500;     6500;     6500;      101;      111;      111;     6500;     6500;     6500;        0;        0;        0; 2.000000; 2.000000; 14866.82;     36.9;      0.1;  2761.33;    198.9;      0.5
     6550;     6550;     6550;      101;      111;      111;     6550;     6550;     6550;        0;        0;        0; 2.000000; 2.000000; 14633.79;     38.4;      0.1;  2830.17;    198.6;      0.5
     6600;     6600;     6600;      101;      111;      111;     6600;     6600;     6600;        0;        0;        0; 2.000000; 2.000000; 14852.83;     38.7;      0.1;  2992.63;    192.1;      0.5
     6650;     6650;     6650;      101;      111;      111;     6650;     6650;     6650;        0;        0;        0; 2.000000; 2.000000; 20903.53;     28.1;      0.1;  2956.72;    198.9;      0.5
     6700;     6700;     6700;      101;      111;      111;     6700;     6700;     6700;        0;        0;        0; 2.000000; 2.000000; 18749.46;     32.1;      0.1;  3014.29;    199.6;      0.5
     6750;     6750;     6750;      101;      111;      111;     6750;     6750;     6750;        0;        0;        0; 2.000000; 2.000000; 15789.88;     39.0;      0.1;  3071.27;    200.3;      0.5
     6800;     6800;     6800;      101;      111;      111;     6800;     6800;     6800;        0;        0;        0; 2.000000; 2.000000; 16386.16;     38.4;      0.1;  3255.50;    193.2;      0.5
     6850;     6850;     6850;      101;      111;      111;     6850;     6850;     6850;        0;        0;        0; 2.000000; 2.000000; 16844.73;     38.2;      0.1;  3217.87;    199.8;      0.5

**Comment by CNugteren** [comment]
OK, so that didn't help unfortunately - it only made things worse. Could still be related to the partition camping issue on AMD GPUs though. Unfortunately I cannot reproduce it on my own AMD GPU, but I'll try to see if I can reproduce it somewhere on another machine.

In the meantime, perhaps it helps to express your large matrix-multiplication as multiple smaller ones? So make either m or n smaller, say a factor 4 or 8 and then concatenate the smaller rectangular results together? But I am afraid that the large leading dimension will actually kill performance, not necessarily the large matrices. Perhaps you can do some experiments with that idea in mind?

**Comment by MigMuc** [comment]
You can consider the issue closed. I observed the same behaviour with clBLAS albeit with higher matrix dimensions.
