### ISSUE TITLE
Error when executing database.py after tuning

### ISSUE THREAD

**Issue by RichardSchulze** [CNugteren/CLBlast#194]
I am using CLBlast version 0.11.0 and I am getting the following output when executing `python ../scripts/database/database.py . ..` after executing the tuners as described in the CLBlast readme:
```
[database] Downloading database from 'https://raw.githubusercontent.com/CNugteren/CLBlast-database/master/database.json'...
[database] Loading database from '../scripts/database/database.json'
[database] Processing './clblast_copy_32.json' with 144 new items
[database] Processing './clblast_copy_64.json' with 144 new items
[database] Processing './clblast_copy_3232.json' with 144 new items
[database] Processing './clblast_copy_6464.json' with 144 new items
[database] Processing './clblast_pad_32.json' with 81 new items
[database] Processing './clblast_pad_64.json' with 81 new items
[database] Processing './clblast_pad_3232.json' with 81 new items
[database] Processing './clblast_pad_6464.json' with 81 new items
[database] Processing './clblast_transpose_32.json' with 60 new items
[database] Processing './clblast_transpose_64.json' with 50 new items
[database] Processing './clblast_transpose_3232.json' with 50 new items
[database] Processing './clblast_transpose_6464.json' with 40 new items
[database] Processing './clblast_padtranspose_32.json' with 20 new items
[database] Processing './clblast_padtranspose_64.json' with 16 new items
[database] Processing './clblast_padtranspose_3232.json' with 16 new items
[database] Processing './clblast_padtranspose_6464.json' with 12 new items
[database] Processing './clblast_xaxpy_32.json' with 96 new items
[database] Processing './clblast_xaxpy_64.json' with 96 new items
[database] Processing './clblast_xaxpy_3232.json' with 96 new items
[database] Processing './clblast_xaxpy_6464.json' with 96 new items
[database] Processing './clblast_xdot_1_32.json' with 6 new items
[database] Processing './clblast_xdot_2_32.json' with 6 new items
[database] Processing './clblast_xdot_1_64.json' with 6 new items
[database] Processing './clblast_xdot_2_64.json' with 6 new items
[database] Processing './clblast_xdot_1_3232.json' with 6 new items
[database] Processing './clblast_xdot_2_3232.json' with 6 new items
[database] Processing './clblast_xdot_1_6464.json' with 6 new items
[database] Processing './clblast_xdot_2_6464.json' with 6 new items
[database] Processing './clblast_xger_32.json' with 181 new items
[database] Processing './clblast_xger_64.json' with 181 new items
[database] Processing './clblast_xger_3232.json' with 181 new items
[database] Processing './clblast_xger_6464.json' with 181 new items
[database] Processing './clblast_xgemm_1_32.json' with 578 new items
[database] Processing './clblast_xgemm_1_64.json' with 578 new items
[database] Processing './clblast_xgemm_1_3232.json' with 578 new items
[database] Processing './clblast_xgemm_1_6464.json' with 370 new items
[database] Processing './clblast_xgemm_direct_1_32.json' with 46 new items
[database] Processing './clblast_xgemm_direct_2_32.json' with 116 new items
[database] Processing './clblast_xgemm_direct_1_64.json' with 46 new items
[database] Processing './clblast_xgemm_direct_2_64.json' with 69 new items
[database] Processing './clblast_xgemm_direct_1_3232.json' with 46 new items
[database] Processing './clblast_xgemm_direct_2_3232.json' with 72 new items
[database] Processing './clblast_xgemm_direct_1_6464.json' with 10 new items
[database] Processing './clblast_xgemm_direct_2_6464.json' with 24 new items
[database] Processing './clblast_xgemv_32.json' with 12 new items
[database] Processing './clblast_xgemv_fast_32.json' with 29 new items
[database] Processing './clblast_xgemv_fast_rot_32.json' with 68 new items
[database] Processing './clblast_xgemv_64.json' with 12 new items
[database] Processing './clblast_xgemv_fast_64.json' with 30 new items
[database] Processing './clblast_xgemv_fast_rot_64.json' with 64 new items
[database] Processing './clblast_xgemv_3232.json' with 12 new items
[database] Processing './clblast_xgemv_fast_3232.json' with 29 new items
[database] Processing './clblast_xgemv_fast_rot_3232.json' with 64 new items
[database] Processing './clblast_xgemv_6464.json' with 12 new items
[database] Processing './clblast_xgemv_fast_6464.json' with 30 new items
[database] Processing './clblast_xgemv_fast_rot_6464.json' with 56 new items
[database] Saving database to '../scripts/database/database.json'
[database] Calculating the best results per device/kernel...
Traceback (most recent call last):
  File "../scripts/database/database.py", line 163, in <module>
    main(sys.argv[1:])
  File "../scripts/database/database.py", line 144, in main
    database_best_results = bests.get_best_results(database)
  File "/path/to/CLBlast/scripts/database/database/bests.py", line 26, in get_best_results
    if result["time"] < time_best:
TypeError: list indices must be integers, not str
```
I have used the tuners and the `datapase.py` script before without any problems. Could you help me sorting this error out?

Many thanks in advance!

**Comment by CNugteren** [comment]
I'm afraid this is because the database format changed in the current master of CLBlast. Therefore, you'll have to download an older copy of `database.json` from https://github.com/CNugteren/CLBlast-database/ (e.g. the one from July 30) and save it as `scripts/database/database.json`.

I'll add tags to the database repository to make this easier.

**Comment by RichardSchulze** [comment]
Thank you for the fast reply!

**Comment by blueberry** [comment]
Richard, are you using 0.11.0 on purpose? 1.0.1 has been available for quite some time now.

**Comment by CNugteren** [comment]
Tags are added, here is the corresponding 0.11.0 version:
https://github.com/CNugteren/CLBlast-database/releases/tag/v0.11.0
