### ISSUE TITLE
Quirky question about performance with 4 GPUS (2x Fiji and 2xEllesmere)

### ISSUE THREAD

**Issue by paolodalberto** [CNugteren/CLBlast#263]
This is to pick your brain and see what could be your prospective about the following performance plots. It is not a real issue it is more a discussion point. Two plots one I created and the other you should be familiar (clBlast vs clBLAS). 

http://www.fastmmw.com/wp-content/uploads/2018/03/BlastSingle.png
http://www.fastmmw.com/wp-content/uploads/2018/03/sgemm_plot.pdf

I am experimenting with Fast Algorithms (Winograd style) and I use two Pro Duo (4 GPUS). One is based on Fiji and the other on Ellesmere. The first plot shows the performance for different algorithms (M7, M23 and M49 that are variations of Winograd algorithm) and using only Fijis and 2xFiji + 2xEllesmere. FLOPS are measured as 2*N^3 ao I can compare to the regular MM and the problem sizes are such as they do not fit into a single GPU.

What puzzles me is that 2xFiji outperforms 2xFiji+2xEllesmere in single precision and only in single precision. In fact, any complex and double precision 4 is better than 2.  http://www.fastmmw.com/2018/03/09/clblas-and-clblast/

This inconsistency makes me wonder. Would you mind to throw at me any ideas you may have?

Cheers

**Comment by paolodalberto** [comment]
Yet as another example to think about. 

I have installed Blast and I make it with my Polaris Pro-Duo (ellesmere) 
http://www.fastmmw.com/wp-content/uploads/2018/03/sgemm_plot.pdf 
This is the plot I show before. 

I reinstalled but now the default device is 2xFiji (ellesmere is 2 and 3) 
[http://www.fastmmw.com/wp-content/uploads/2018/03/2.32.pdf](url)

This difference is only for the SGEMM .... it may be that the performance of device 2 and 3 got so bad that overall performance is worse. My implementation does not deploy queues and the algorithm goes in steps so that the slowest GPUs determines the pace. 

what do you think it is happening ?

**Comment by CNugteren** [comment]
Your last graph doesn't seem to match your text?

I can't say much about your final application and how you implemented multi-GPU. My task is to make sure the GEMM kernels themselves are fast :-) From the CLBlast benchmark plots you showed it doesn't always seem to be the case, sometimes clBLAS is faster. I am curious to know whether this is still the case after you tuned. Because if so, we would need to make some improvements.

For reference, [here](https://cnugteren.github.io/clblast/results/tahiti.html) are some results on an older AMD GPU.

**Comment by paolodalberto** [comment]
Let me go a step back and talk about these two plots. 
http://www.fastmmw.com/wp-content/uploads/2018/03/sgemm_plot.pdf
http://www.fastmmw.com/wp-content/uploads/2018/03/2.32.pdf

These are the plots for SGEMM for ellesmere on a Polaris Pro Duo. The performance plots are different (right?). 

The first plot, I created the first time installed clBlast when there was  only the Polaris and the device number was zero.  

The second plot. Now the system has 2xFiji device 0 and 1, and 2x ellesmere device 2 and 3.  I plot the performance for device 2.  The polaris pro duo stayed into the same PCI slot and drives the monitors.  

Can you see the performance difference ?

**Comment by paolodalberto** [comment]
funny I cannot reproduce 
http://www.fastmmw.com/wp-content/uploads/2018/03/sgemm_plot.pdf

I removed the fiji and rebuilt. nothing. So the bad performance of hte mix performance is due to the fact that I do not create a queue ....

so if you have not further ideas we can close this ...

**Comment by paolodalberto** [comment]
OK I got it ... it is the opencl version using /roc/opencl/lib + ellesmere ... I got the best performance.

**Comment by paolodalberto** [comment]
with amdgpu-pro + fiji I get the better performance ....

**Comment by paolodalberto** [comment]
OK I am getting somewhere .... although  I do not know how to handle this different builts in a single application.

**Comment by CNugteren** [comment]
It is a bit messy indeed with those different implementations from AMD. One thing to note is that there is a missing feature in ROCm which causes device identification to fail (https://github.com/RadeonOpenCompute/ROCm/issues/215). Thus, this might lead to different tuning parameters being chosen.

But in any case, I would first tune the appropriate kernels before making any conclusions here.

**Comment by paolodalberto** [comment]
Alas I cannot tune it ...  see previous problem

**Comment by paolodalberto** [comment]
I can create for device 2 (ellesmere)

-rw-rw-r-- 1 paolo paolo 115874 Mar 13 18:38 clblast_xgemm_1_32.json
-rw-rw-r-- 1 paolo paolo 53902 Mar 13 18:40 clblast_xgemm_2_32.json

for the clBlast built using amdgpu-pro

`paolo@fastmmwfusion:~/fusion/paolo/Desktop/MM/CLBlast/gpupro$ head -n 20 clblast_xgemm_?_32.json
==> clblast_xgemm_1_32.json <==
{
"kernel_family": "xgemm_1",
"precision": "32",
"best_kernel": "Xgemm",
"best_time": "0.62",
"best_parameters": "KWG=32 KWI=2 MDIMA=8 MDIMC=8 MWG=64 NDIMB=16 NDIMC=16 NWG=64 PRECISION=32 SA=1 SB=1 STRM=0 STRN=0 VWM=4 VWN=4",
"arg_m": "1024",
"arg_n": "1024",
"arg_k": "1024",
"arg_alpha": "2.00",
"arg_beta": "2.00",
"clblast_device_type": "GPU",
"clblast_device_vendor": "AMD",
"clblast_device_architecture": "Fiji",
"clblast_device_name": "Radeon (TM) Pro Duo",
"device": "Fiji",
"platform_vendor": "Advanced Micro Devices, Inc.",
"platform_version": "OpenCL 2.1 AMD-APP (2527.3)",
"device_vendor": "Advanced Micro Devices, Inc.",
"device_type": "GPU",

==> clblast_xgemm_2_32.json <==
{
"kernel_family": "xgemm_2",
"precision": "32",
"best_kernel": "Xgemm",
"best_time": "0.63",
"best_parameters": "KWG=16 KWI=2 MDIMA=8 MDIMC=8 MWG=64 NDIMB=8 NDIMC=16 NWG=64 PRECISION=32 SA=1 SB=1 STRM=0 STRN=1 VWM=4 VWN=2",
"arg_m": "1024",
"arg_n": "1024",
"arg_k": "1024",
"arg_alpha": "2.00",
"arg_beta": "2.00",
"clblast_device_type": "GPU",
"clblast_device_vendor": "AMD",
"clblast_device_architecture": "Fiji",
"clblast_device_name": "Radeon (TM) Pro Duo",
"device": "Fiji",
"platform_vendor": "Advanced Micro Devices, Inc.",
"platform_version": "OpenCL 2.1 AMD-APP (2527.3)",
"device_vendor": "Advanced Micro Devices, Inc.",
"device_type": "GPU",`

it looks like it does not recognize the device (Fiji?)

and rocm

`paolo@fastmmwfusion:~/fusion/paolo/Desktop/MM/CLBlast/rocm$ head -n 20 clblast_xgemm_?_32.json
==> clblast_xgemm_1_32.json <==
{
"kernel_family": "xgemm_1",
"precision": "32",
"best_kernel": "Xgemm",
"best_time": "1.19",
"best_parameters": "KWG=32 KWI=2 MDIMA=8 MDIMC=8 MWG=64 NDIMB=8 NDIMC=8 NWG=64 PRECISION=32 SA=0 SB=0 STRM=0 STRN=0 VWM=4 VWN=4",
"arg_m": "1024",
"arg_n": "1024",
"arg_k": "1024",
"arg_alpha": "2.00",
"arg_beta": "2.00",
"clblast_device_type": "GPU",
"clblast_device_vendor": "AMD",
"clblast_device_architecture": "Fiji",
"clblast_device_name": "Device 67c4",
"device": "gfx803",
"platform_vendor": "Advanced Micro Devices, Inc.",
"platform_version": "OpenCL 2.1 AMD-APP.internal (2576.0)",
"device_vendor": "Advanced Micro Devices, Inc.",
"device_type": "GPU",

==> clblast_xgemm_2_32.json <==
{
"kernel_family": "xgemm_2",
"precision": "32",
"best_kernel": "Xgemm",
"best_time": "0.89",
"best_parameters": "KWG=32 KWI=2 MDIMA=8 MDIMC=32 MWG=128 NDIMB=16 NDIMC=8 NWG=128 PRECISION=32 SA=1 SB=1 STRM=1 STRN=1 VWM=2 VWN=2",
"arg_m": "1024",
"arg_n": "1024",
"arg_k": "1024",
"arg_alpha": "2.00",
"arg_beta": "2.00",
"clblast_device_type": "GPU",
"clblast_device_vendor": "AMD",
"clblast_device_architecture": "Fiji",
"clblast_device_name": "Device 67c4",
"device": "gfx803",
"platform_vendor": "Advanced Micro Devices, Inc.",
"platform_version": "OpenCL 2.1 AMD-APP.internal (2576.0)",
"device_vendor": "Advanced Micro Devices, Inc.",
"device_type": "GPU",`

this will help you ?

**Comment by paolodalberto** [comment]
and for device 0 (Fiji) for rocm
`==> clblast_xgemm_1_32.json <==
{
  "kernel_family": "xgemm_1",
  "precision": "32",
  "best_kernel": "Xgemm",
  "best_time": "0.86",
  "best_parameters": "KWG=32 KWI=2 MDIMA=16 MDIMC=16 MWG=64 NDIMB=8 NDIMC=8 NWG=64 PRECISION=32 SA=1 SB=1 STRM=0 STRN=0 VWM=2 VWN=2",
  "arg_m": "1024",
  "arg_n": "1024",
  "arg_k": "1024",
  "arg_alpha": "2.00",
  "arg_beta": "2.00",
  "clblast_device_type": "GPU",
  "clblast_device_vendor": "AMD",
  "clblast_device_architecture": "Fiji",
  "clblast_device_name": "Fiji [Radeon R9 FURY / NANO Series]",
  "device": "gfx803",
  "platform_vendor": "Advanced Micro Devices, Inc.",
  "platform_version": "OpenCL 2.1 AMD-APP.internal (2576.0)",
  "device_vendor": "Advanced Micro Devices, Inc.",
  "device_type": "GPU",

==> clblast_xgemm_2_32.json <==
{
  "kernel_family": "xgemm_2",
  "precision": "32",
  "best_kernel": "Xgemm",
  "best_time": "0.84",
  "best_parameters": "KWG=32 KWI=2 MDIMA=16 MDIMC=16 MWG=128 NDIMB=8 NDIMC=16 NWG=128 PRECISION=32 SA=1 SB=1 STRM=0 STRN=1 VWM=4 VWN=4",
  "arg_m": "1024",
  "arg_n": "1024",
  "arg_k": "1024",
  "arg_alpha": "2.00",
  "arg_beta": "2.00",
  "clblast_device_type": "GPU",
  "clblast_device_vendor": "AMD",
  "clblast_device_architecture": "Fiji",
  "clblast_device_name": "Fiji [Radeon R9 FURY / NANO Series]",
  "device": "gfx803",
  "platform_vendor": "Advanced Micro Devices, Inc.",
  "platform_version": "OpenCL 2.1 AMD-APP.internal (2576.0)",
  "device_vendor": "Advanced Micro Devices, Inc.",
  "device_type": "GPU",
`

**Comment by paolodalberto** [comment]
BTW: 
` ls -lrt | tail 
-rwxrwxr-x   1 paolo paolo 1028384 Mar 13 18:33 clblast_test_xspmv
-rwxrwxr-x   1 paolo paolo 1115784 Mar 13 18:34 clblast_test_xswap
-rwxrwxr-x   1 paolo paolo 1112064 Mar 13 18:34 clblast_test_xcopy
-rwxrwxr-x   1 paolo paolo 1073792 Mar 13 18:34 clblast_test_xtrsv
-rwxrwxr-x   1 paolo paolo 1116568 Mar 13 18:34 clblast_test_xtbmv
drwxrwxr-x 132 paolo paolo   12288 Mar 13 18:34 CMakeFiles
-rw-rw-r--   1 paolo paolo   48776 Mar 13 18:42 sgemm_benchmarks.json
-rw-rw-r--   1 paolo paolo   26762 Mar 13 18:42 sgemm_plot.pdf
-rw-rw-r--   1 paolo paolo  115922 Mar 13 18:59 clblast_xgemm_1_32.json
-rw-rw-r--   1 paolo paolo   53949 Mar 13 19:01 clblast_xgemm_2_32.json
paolo@fastmmwfusion:~/fusion/paolo/Desktop/MM/CLBlast/rocm$ python ../scripts/database/database.py . ..
[database] Loading database from '../scripts/database/database.json'
[database] Processing './sgemm_benchmarks.json' Traceback (most recent call last):
  File "../scripts/database/database.py", line 158, in <module>
    main(sys.argv[1:])
  File "../scripts/database/database.py", line 113, in main
    imported_data = io.load_tuning_results(file_json)
  File "/home/paolo/fusion/paolo/Desktop/MM/CLBlast/scripts/database/database/io.py", line 84, in load_tuning_results
    json_data["kernel_family"] = re.sub(r'_\d+', '', json_data["kernel_family"])
KeyError: 'kernel_family'
`

**Comment by paolodalberto** [comment]
I think I can tune sgemm 
and store it in the DB 
[sgem2_plot.pdf](https://github.com/CNugteren/CLBlast/files/1812225/sgem2_plot.pdf)
[sgemm_plot.pdf](https://github.com/CNugteren/CLBlast/files/1812226/sgemm_plot.pdf)

one is the default and the other is the tuned

**Comment by paolodalberto** [comment]
I guess as a function of the opencl naming different codes are executed although the GPU did not change.

**Comment by paolodalberto** [comment]
Tuned sgem for my fiji and ellesmere
[sgemm_plot_2.pdf](https://github.com/CNugteren/CLBlast/files/1812319/sgemm_plot_2.pdf)
[sgemm_plot.pdf](https://github.com/CNugteren/CLBlast/files/1812320/sgemm_plot.pdf)

`        { "Ellesmere", {
          { Name{"AMD Radeon (TM) Pro WX 7100 Graphics              "}, Params{ 32, 2, 8, 16, 128, 8, 16, 128, 1, 1, 1, 1, 4, 2 } },
          { Name{"AMD Radeon RX 480                                 "}, Params{ 32, 2, 8, 8, 16, 16, 16, 64, 1, 1, 0, 0, 1, 2 } },
          { kDeviceNameDefault                                        , Params{ 32, 2, 16, 16, 64, 8, 8, 64, 1, 1, 0, 0, 4, 4 } },
        } },
        { "Fiji", {
          { Name{"AMD Radeon R9 Fury X                              "}, Params{ 32, 2, 16, 16, 64, 16, 16, 64, 1, 1, 0, 0, 4, 4 } },
          { Name{"AMD Radeon R9 M370X Compute Engine                "}, Params{ 32, 2, 16, 16, 64, 8, 16, 128, 0, 0, 0, 0, 2, 8 } },
          { Name{"Radeon (TM) Pro Duo                               "}, Params{ 32, 2, 32, 32, 128, 8, 8, 64, 1, 1, 1, 0, 4, 8 } },
          { kDeviceNameDefault                                        , Params{ 32, 2, 16, 16, 64, 8, 8, 64, 1, 1, 0, 0, 2, 4 } },
`

**Comment by paolodalberto** [comment]
Now 2xFiji +2xEllesmere GPUs 
paolo@fastmmwfusion:~/fusion/paolo/Desktop/MM/Epyc/fmm$ small_body_cp Single 30000 0 4 0   
```
30000 M7---0-0-4
 M7   OPS 5.400000e+13 GFLOPS COLD 3.761559e+03
 M7   OPS 5.400000e+13 GFLOPS HOT  3.669280e+03
30000 M23--0-0-4
 M23  OPS 5.400000e+13 GFLOPS COLD 3.652032e+03
 M23  OPS 5.400000e+13 GFLOPS HOT  4.771847e+03
30000 M49--0-0-4
 M49  OPS 5.400000e+13 GFLOPS COLD 3.451300e+03
 M49  OPS 5.400000e+13 GFLOPS HOT  3.969361e+03
```

are better than 2xFiji 
paolo@fastmmwfusion:~/fusion/paolo/Desktop/MM/Epyc/fmm$ small_body_cp Single 30000 0 2 0   
```
30000 M7---0-0-2
 M7   OPS 5.400000e+13 GFLOPS COLD 2.627523e+03
 M7   OPS 5.400000e+13 GFLOPS HOT  2.433948e+03
30000 M23--0-0-2
 M23  OPS 5.400000e+13 GFLOPS COLD 3.707885e+03
 M23  OPS 5.400000e+13 GFLOPS HOT  4.096836e+03
30000 M49--0-0-2
 M49  OPS 5.400000e+13 GFLOPS COLD 3.082491e+03
 M49  OPS 5.400000e+13 GFLOPS HOT  3.347279e+03
```
and better than 2xellesmere
```
30000 M7---0-2-4
 M7   OPS 5.400000e+13 GFLOPS COLD 3.356864e+03
 M7   OPS 5.400000e+13 GFLOPS HOT  3.629186e+03
30000 M23--0-2-4
 M23  OPS 5.400000e+13 GFLOPS COLD 2.905337e+03
 M23  OPS 5.400000e+13 GFLOPS HOT  3.189670e+03
30000 M49--0-2-4
 M49  OPS 5.400000e+13 GFLOPS COLD 2.602010e+03
 M49  OPS 5.400000e+13 GFLOPS HOT  2.880442e+03
```
