### ISSUE TITLE
database.py downloads external database, will fail on version mismatch

### ISSUE THREAD

**Issue by gcp** [CNugteren/CLBlast#75]
python ../scripts/database/database.py . ..
## Loading the database from disk...
Traceback (most recent call last):
  File "../scripts/database/database.py", line 283, in <module>
    database = LoadDatabase(file_db)
  File "../scripts/database/database.py", line 66, in LoadDatabase
    return pd.read_pickle(filename)
  File "/usr/lib/python2.7/dist-packages/pandas/io/pickle.py", line 60, in read_pickle
    return try_read(path)
  File "/usr/lib/python2.7/dist-packages/pandas/io/pickle.py", line 57, in try_read
    return pc.load(fh, encoding=encoding, compat=True)
  File "/usr/lib/python2.7/dist-packages/pandas/compat/pickle_compat.py", line 116, in load
    return up.load()
  File "/usr/lib/python2.7/pickle.py", line 864, in load
    dispatch[key](self)
  File "/usr/lib/python2.7/pickle.py", line 1096, in load_global
    klass = self.find_class(module, name)
  File "/usr/lib/python2.7/pickle.py", line 1130, in find_class
    __import__(module)
ImportError: No module named indexes.base

From a bit of digging, the database format isn't compatible between pandas versions.

**Comment by CNugteren** [comment]
Hmm, that's not nice. I am not much of a Python expert, but hopefully it is just a minimum version requirement of Pandas? Can you try with a newer (or older?) version or is that too difficult?

**Comment by gcp** [comment]
Throwing out the distro package (Ubuntu 16.04 ships with 0.17.1) and doing a "pip install pandas" which brought int pandas-0.18.1 fixed it. So yes, looks like a version requirement there.

**Comment by CNugteren** [comment]
You are right. It seems that the database is not backwards compatible. For now I've added a small message in the script reporting the current and required version. But better would be to re-create the database based on an earlier version using pandas 0.17.x. That way I think both 0.17.x and 0.18.x will be able to use it.

**Comment by CNugteren** [comment]
I have now re-created the database with pandas 0.17. So at least it now works with 0.17, but I believe it should now still work with newer versions. I'll keep in mind next time not to create a database with pandas 0.18.

Also, there is still a small notice about the version requirement and the current version, so I guess this closes this issue.
